const COURSESAPIURL = {
  ADDRESS: 'http://localhost:3001',
};

const EUROPE_CITIES = ['AMSTERDAM', 'BAD SALZUFLEN', 'BERLIN', 'COPENHAGEN', 'DRESDEN', 'DUBLIN',
  'Erfurt', 'ESSEN', 'FRANKFURT', 'FREIBURG', 'GOTHENBURG', 'HAMBURG', 'ITALY', 'LEIPZIG', 'LJUNGBY', 'MUNICH',
  'OLDENBURG', 'OSLO', 'POLAND', 'ROTTERDAM', 'STOCKHOLM', 'VIENNA', 'Wuppertal', 'ZEVENAAR',
];

module.exports = { COURSESAPIURL, EUROPE_CITIES };
